version: '3.8'

services:
  mariadb:
    image: mariadb
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Pruebas
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
